# Changes here will be overwritten by Copier.
_commit: 27dbd6c
_src_path: gh:Bullish-Design/templateer
author_email: BullishDesignLLC@gmail.com
author_fullname: Bullish Design
author_username: Bullish-Design
copyright_date: '2025'
copyright_holder: Bullish Design
copyright_holder_email: BullishDesignLLC@gmail.com
copyright_license: ISC
insiders: false
project_description: Copier template structure to quickly generate uv scripts
project_name: Scripts
python_package_command_line_name: scripts
python_package_distribution_name: scripts
python_package_import_name: scripts
repository_name: scripts
repository_namespace: Bullish-Design
repository_provider: github.com

