# Changes here will be overwritten by Copier.
_commit: 5205fbd
_src_path: gh:Bullish-Design/scripts
author_email: bullishdesignengineering@gmail.com
author_fullname: Bullish Design
author_username: Bullish-Design
copyright_date: ''
copyright_holder: Bullish Design
copyright_holder_email: bullishdesignengineering@gmail.com
copyright_license: ISC
project_description: Test-script script.
project_name: test-script
python_package_command_line_name: test-script
python_package_distribution_name: test-script
python_package_import_name: test-script
repository_name: test-script
repository_namespace: Bullish-Design
repository_provider: github.com

